version: '3.9'
services:
  postgres-dev:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data

  pgadmin-dev:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    depends_on:
      - postgres-dev
